<?php

/**
 * Admin: Créer un utilisateur
 * POST /api/admin/users-create.php
 *
 * Deprecated: use POST /api/persons/create.php instead.
 * This file is kept for backwards compatibility.
 */

require_once __DIR__ . '/../bootstrap.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    Response::error('Méthode non autorisée', 405);
}

Auth::requireAdmin();

try {
    $data = json_decode(file_get_contents('php://input'), true);

    if (empty($data['email']) || empty($data['nom']) || empty($data['prenom'])) {
        Response::error('Email, nom et prénom requis', 400);
    }

    if (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
        Response::error('Email invalide', 400);
    }

    $chk = $db->prepare("SELECT id FROM persons WHERE email = ? LIMIT 1");
    $chk->execute([$data['email']]);
    if ($chk->fetch()) {
        Response::error('Cet email est déjà utilisé', 409);
    }

    $isAutoGenerated = empty($data['password']);
    $password        = $isAutoGenerated ? bin2hex(random_bytes(8)) : $data['password'];
    $password_hash   = Auth::hashPassword($password);
    $role            = isset($data['role']) && in_array($data['role'], ['user', 'admin']) ? $data['role'] : 'user';
    $id              = UuidHelper::generate();

    // Code parrainage unique
    $code = 'CPF' . strtoupper(substr(str_replace('-', '', $id), 0, 6));
    $chkCode = $db->prepare("SELECT id FROM persons WHERE code_parrainage = ? LIMIT 1");
    $chkCode->execute([$code]);
    while ($chkCode->fetch()) {
        $code = 'CPF' . strtoupper(bin2hex(random_bytes(3)));
        $chkCode->execute([$code]);
    }

    $db->prepare("
        INSERT INTO persons
          (id, email, password_hash, nom, prenom, telephone,
           role, statut, source, crm_statut,
           profession, entreprise, code_parrainage,
           created_at, updated_at)
        VALUES
          (:id, :email, :pwd, :nom, :prenom, :tel,
           :role, 'actif', 'inscription', 'client',
           :profession, :entreprise, :code,
           NOW(), NOW())
    ")->execute([
        ':id'         => $id,
        ':email'      => trim($data['email']),
        ':pwd'        => $password_hash,
        ':nom'        => trim($data['nom']),
        ':prenom'     => trim($data['prenom']),
        ':tel'        => $data['telephone'] ?? null,
        ':role'       => $role,
        ':profession' => $data['profession'] ?? null,
        ':entreprise' => $data['entreprise'] ?? null,
        ':code'       => $code,
    ]);

    $db->prepare("
        INSERT INTO parrainages (id, parrain_id, code_parrain, parraines, recompenses_totales)
        VALUES (:id, :parrain_id, :code, 0, 0)
    ")->execute([
        ':id'        => UuidHelper::generate(),
        ':parrain_id'=> $id,
        ':code'      => $code,
    ]);

    // Email d'accueil si mot de passe auto-généré
    $emailSent = false;
    if (!empty($data['email'])) {
        try {
            $body = Mailer::wrapInLayout(
                'Bienvenue sur Coffice',
                '<h2>Bonjour ' . htmlspecialchars($data['prenom']) . ',</h2>'
                . '<p>Un compte a été créé pour vous sur la plateforme Coffice.</p>'
                . Mailer::infoBox([
                    'Email'                   => htmlspecialchars($data['email']),
                    'Mot de passe temporaire' => $password,
                ])
                . '<p>Veuillez vous connecter et changer votre mot de passe dès que possible.</p>'
                . Mailer::ctaButton('https://coffice.dz/connexion', 'Se connecter'),
                'Vos identifiants Coffice'
            );
            $emailSent = Mailer::send($data['email'], 'Bienvenue sur Coffice — Vos identifiants de connexion', $body);
        } catch (Exception $mailErr) {
            Logger::warning('Welcome email failed on user create', ['error' => $mailErr->getMessage(), 'person_id' => $id]);
        }
    }

    Logger::info('Admin created user', [
        'admin_id'   => $authUser['id'] ?? null,
        'person_id'  => $id,
        'email'      => $data['email'],
        'email_sent' => $emailSent,
    ]);

    Response::success([
        'id'              => $id,
        'email'           => $data['email'],
        'nom'             => $data['nom'],
        'prenom'          => $data['prenom'],
        'telephone'       => $data['telephone'] ?? null,
        'profession'      => $data['profession'] ?? null,
        'entreprise'      => $data['entreprise'] ?? null,
        'code_parrainage' => $code,
        'role'            => $role,
        'statut'          => 'actif',
        'created_at'      => date('Y-m-d H:i:s'),
        'temp_password'   => $isAutoGenerated ? $password : null,
        'email_sent'      => $emailSent,
    ], 'Utilisateur créé avec succès', 201);

} catch (PDOException $e) {
    Logger::error('Database error creating user', ['error' => $e->getMessage()]);
    Response::error('Erreur lors de la création: ' . $e->getMessage(), 500);
} catch (Exception $e) {
    Logger::error('Error creating user', ['error' => $e->getMessage()]);
    Response::error('Une erreur est survenue: ' . $e->getMessage(), 500);
}
